<%= render_erb 'images/Dockerfile.npm.erb' %>

# By default, TSLint looks for a configuration file named tslint.json in the directory of the file being linted and, if not found, searches ancestor directories.
COPY --chown=<%= chown %> images/<%= analyzer %>/tslint.json ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
