FROM sider/devon_rex_base:2.6.0

<%= render_erb 'images/Dockerfile.base.erb' %>

USER root
ARG MISSPELL_VERSION=0.3.4
RUN curl -sSL -o install-misspell.sh https://git.io/misspell && \
    sh ./install-misspell.sh -b /usr/local/bin "v${MISSPELL_VERSION}" && \
    rm ./install-misspell.sh
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.end.erb' %>
