<%= render_erb 'images/Dockerfile.ruby.erb' %>

COPY --chown=<%= chown %> \
     images/<%= analyzer %>/.reek.yml \
     images/<%= analyzer %>/config.reek \
     ${RUNNER_USER_HOME}/

<%= render_erb 'images/Dockerfile.end.erb' %>
