module Runners
  module Testing
    class Smoke
      include Minitest::Assertions
      include UnificationAssertion
      include Tmpdir

      class TestParams
        attr_reader name: String
        attr_reader pattern: Hash[Symbol, untyped]
        attr_reader offline: bool

        def initialize: (name: String, pattern: Hash[Symbol, untyped], offline: bool) -> void
      end

      def self.only?: (String) -> bool
      def self.add_test: (String, **Hash[Symbol, untyped]) -> void
      def self.add_offline_test: (String, **Hash[Symbol, untyped]) -> void
      def self.check_duplicate: (String) -> void
      def self.build_pattern: (type: String,
                               ?guid: String,
                               ?timestamp: Symbol,
                               ?issues: Array[untyped] | nil,
                               ?message: String | Regexp | nil,
                               ?analyzer: Hash[Symbol, untyped] | nil,
                               ?class: String | nil,
                               ?backtrace: Array[String] | nil,
                               ?inspect: String | Regexp | nil,
                               ?warnings: Array[Hash[Symbol, untyped]],
                               ?ci_config: Hash[Symbol, untyped] | Symbol,
                               ?config_file: String | Symbol,
                               ?version: String | Symbol
                              ) -> Hash[Symbol, untyped]
      def self.tests: -> Array[TestParams]

      attr_reader argv: Array[String]
      attr_reader data_container: String
      attr_reader data_smoke_path: Pathname

      def docker_image: -> String
      def entrypoint: -> Pathname
      def expectations: -> Pathname
      def initialize: (Array[String]) -> void
      def run: () -> void
      def run_test: (TestParams, StringIO) -> Symbol
      def unify_result: (untyped, untyped, StringIO) -> bool
      def with_data_container: [X] { () -> X } -> X
      def command_line: (params: TestParams, repo_dir: String, base: String, head: String) -> Array[String]
      type repo_info = { dir: String, base: String, head: String }
      def prepare_git_repository: (workdir: Pathname, smoke_target: Pathname, out: StringIO) -> repo_info
      def debug?: () -> bool
      def debug_trace?: () -> bool
      def sh!: (*String, out: StringIO, ?exception: bool) -> [String, String]
      def colored_pretty_inspect: (untyped, ?multiline: bool) -> String
    end
  end
end
