module OpenSSL
end

class OpenSSL::Cipher
  def initialize: (String) -> void
  def decrypt: () -> void
  def iv_len: () -> Integer
  def pkcs5_keyivgen: (String, ?String?, ?Integer, ?String) -> void
  def update: (String) -> String
  def final: () -> String
end
