class URI
  def self.parse: (String) -> URI
  def self.join: (*String) -> URI

  def path: () -> String
  def scheme: () -> String
  def host: () -> String
  def hostname: () -> String
  def port: () -> Integer
  def userinfo=: (String) -> String
end
