class Runners::Changes
  attr_reader changed_paths: Array[Pathname]

  attr_reader unchanged_paths: Array[Pathname]

  attr_reader untracked_paths: Array[Pathname]

  attr_reader patches: GitDiffParser::Patches?

  def initialize: (changed_paths: Array[Pathname], unchanged_paths: Array[Pathname], untracked_paths: Array[Pathname], patches: GitDiffParser::Patches?) -> void

  def delete_unchanged: (dir: Pathname, ?except: Array[String], ?only: Array[String]) { (Pathname) -> void } -> void

  def include?: (Issue) -> bool

  def self.calculate: (base_dir: Pathname, head_dir: Pathname, working_dir: Pathname, patches: GitDiffParser::Patches?) -> instance
end
