class Runners::CLI
  attr_reader stdout: ::IO
  attr_reader stderr: ::IO
  attr_reader guid: String
  attr_reader analyzer: String
  attr_reader options: Options

  def initialize: (argv: Array[String], stdout: ::IO, stderr: ::IO) -> void
  def with_working_dir: [T] { (Pathname) -> T } -> T
  def processor_class: () -> untyped # FIXME
  def run: () -> result
  def io: () -> IO
  def sensitive_strings: () -> Array[String]
end
