class GitBlameInfo < Struct[untyped]
  attr_accessor commit: String
  attr_accessor original_line: Integer
  attr_accessor final_line: Integer
  attr_accessor line_hash: String

  def self.parse: (String porelain_output) -> Array[self]
end
