module Runners
end

class Runners::IO
  attr_reader ios: untyped

  def initialize: (*untyped ios) -> untyped

  def write: (*untyped args) -> untyped

  def flush: (*untyped args) -> untyped

  def flush!: () -> untyped
end

Runners::IO::REQUIRED_METHODS_FOR_IOS: untyped
