class Runners::IO
  attr_reader ios: Array[::IO | Runners::IO::AwsS3]

  def initialize: (*(::IO | Runners::IO::AwsS3) ios) -> void
  def write: (String str) -> void
  def flush: () -> void
  def flush!: () -> void
end

Runners::IO::REQUIRED_METHODS_FOR_IOS: Array[Symbol]
