class Runners::Options
  attr_reader stdout: ::IO
  attr_reader stderr: ::IO
  attr_reader source: Options::GitSource | Options::ArchiveSource
  attr_reader ssh_key: String?
  attr_reader io: Runners::IO

  def initialize: (::IO stdout, ::IO stderr) -> void
  def parse_options: () -> { source: untyped, outputs: Array[String]?, ssh_key: String? }
end

class Runners::Options::GitSource
  attr_accessor head: String
  attr_accessor base: String?
  attr_accessor git_http_url: String
  attr_accessor owner: String
  attr_accessor repo: String
  attr_accessor git_http_userinfo: String?
  attr_accessor pull_number: Integer?

  def initialize: (head: String, ?base: String, git_http_url: String,
                   owner: String, repo: String, ?git_http_userinfo: String, ?pull_number: Integer) -> void
end

class Runners::Options::ArchiveSource
  attr_accessor head: String
  attr_accessor head_key: String?
  attr_accessor base: String?
  attr_accessor base_key: String?

  def initialize: (head: String, ?head_key: String, ?base: String, ?base_key: String) -> void
  def http?: () -> bool
  def file?: () -> bool
end
