# AwsS3IO expects AWS credentials set with environment variables or an instance profile.
# So, before using this, make sure AWS credentials available.
# Also, prepare the S3 bucket and allow this instance to upload an S3 object.
class Runners::IO::AwsS3
  def self.parse_s3_uri!: (untyped s3_uri) -> untyped

  attr_reader uri: untyped

  attr_reader bucket_name: untyped

  attr_reader object_name: untyped

  attr_reader tempfile: untyped

  attr_reader written_items: untyped

  attr_reader client: untyped

  # @param uri [String]
  def initialize: (untyped uri) -> untyped

  def write: (*untyped args) -> untyped

  def flush: (*untyped args) -> untyped

  def should_flush?: () -> untyped

  def flush!: () -> untyped

  def flush_to_s3!: () -> untyped
end

# @type const BUFFER_SIZE: Integer
Runners::IO::AwsS3::BUFFER_SIZE: ::Integer
