module Runners
  module Schema
    class OptionsSchema < StrongJSON
      def source: -> StrongJSON::Type::Enum[untyped]
      def payload: -> StrongJSON::Type::Object[untyped]
    end
    Options: OptionsSchema
  end
end
