module Runners
  module Schema
    type command_line_trace = {
      trace: :command_line,
      command_line: Array[String],
      recorded_at: String
    }

    type status_trace = {
      trace: :status,
      status: Integer,
      recorded_at: String
    }

    type stdout_trace = {
      trace: :stdout,
      string: String,
      recorded_at: String
    }

    type stderr_trace = {
      trace: :stderr,
      string: String,
      recorded_at: String
    }

    type message_trace = {
      trace: :message,
      message: String,
      recorded_at: String
    }

    type header_trace = {
      trace: :header,
      message: String,
      recorded_at: String
    }

    type warning_trace = {
      trace: :warning,
      string: String,
      file: String?,
      recorded_at: String
    }

    type ci_config_trace = {
      trace: :ci_config,
      content: untyped,
      recorded_at: String
    }

    type error_trace = {
      trace: :error,
      message: String,
      recorded_at: String
    }

    type any_trace = command_line_trace
                   | status_trace
                   | stdout_trace
                   | stderr_trace
                   | message_trace
                   | header_trace
                   | warning_trace
                   | ci_config_trace
                   | error_trace

    class TraceSchema < StrongJSON
      def command_line: () -> StrongJSON::Type::Object[command_line_trace]
      def status: () -> StrongJSON::Type::Object[status_trace]
      def stdout: () -> StrongJSON::Type::Object[stdout_trace]
      def stderr: () -> StrongJSON::Type::Object[stderr_trace]
      def message: () -> StrongJSON::Type::Object[message_trace]
      def header: () -> StrongJSON::Type::Object[header_trace]
      def warning: () -> StrongJSON::Type::Object[warning_trace]
      def ci_config: () -> StrongJSON::Type::Object[ci_config_trace]
      def error: () -> StrongJSON::Type::Object[error_trace]
      def anything: () -> StrongJSON::Type::Enum[any_trace]
    end
    Trace: TraceSchema
  end
end
