module Runners
end

class Runners::Processor::ScssLint < Processor
  include Ruby

  def analyzer_bin: () -> untyped

  def analyzer_name: () -> untyped

  def self.ci_config_section_name: () -> untyped

  def analyzer_version: () -> untyped

  def setup: () { () -> untyped } -> untyped

  def analyze: (untyped changes) -> untyped

  def check_runner_config: (untyped config) { (untyped) -> untyped } -> untyped

  def scss_lint_config: (untyped config) -> untyped

  # @param stdout [String]
  def parse_result: (untyped stdout) -> untyped

  def run_analyzer: (untyped options) -> untyped
end

Runners::Processor::ScssLint::Schema: untyped

# https://github.com/brigade/scss-lint#exit-status-codes
Runners::Processor::ScssLint::EXIT_CODE_FILES_NOT_EXIST: ::Integer
