class Runners::Workspace::Git < Workspace
  private
  def try_count: () -> Integer
  def sleep_lambda: () -> ^(Integer) -> Numeric
  def remote_url: () -> URI
  def git_fetch_args: () -> Array[String]
end
