module Runners::Ruby::GemInstaller::Source
  def self.create: (untyped gems_item) -> untyped
end

class Runners::Ruby::GemInstaller::Source::Base
  def rubygems?: () -> untyped

  def git?: () -> untyped

  def default?: () -> untyped
end

# @see https://bundler.io/man/gemfile.5.html#SOURCE
class Runners::Ruby::GemInstaller::Source::Rubygems < Base
  attr_reader source: untyped

  def initialize: (?untyped source) -> untyped

  def rubygems?: () -> untyped

  def default?: () -> untyped

  def ==: (untyped other) -> untyped

  def hash: () -> untyped

  def to_s: () -> untyped
end

# @see https://bundler.io/man/gemfile.5.html#GIT
class Runners::Ruby::GemInstaller::Source::Git < Base
  attr_reader repo: untyped

  attr_reader ref: untyped

  attr_reader branch: untyped

  attr_reader tag: untyped

  def initialize: (untyped repo, ?ref: untyped? ref, ?branch: untyped? branch, ?tag: untyped? tag) -> untyped

  def git?: () -> untyped

  def ==: (untyped other) -> untyped

  def hash: () -> untyped

  def to_s: () -> untyped
end
