module Runners
  class Processor::Checkstyle < Processor
    include Java

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[Schema::java_runner_config]
    end
    Schema: SchemaClass

    OFFICIAL_RULE_NAMESPACE: String

    private
    def checkstyle_args: () -> Array[String]
    def construct_result: (REXML::Document) { (Issue) -> untyped } -> void
    def normalize_id: (untyped rule_id) -> untyped
    def build_links: (untyped rule_id) -> Array[String]
    def config_file: () -> untyped
    def check_directory: () -> untyped
    def excluded_directories: () -> untyped
    def ignored_severities: () -> untyped
    def array: (untyped value) -> untyped
  end
end
