module Runners
  class Processor::ClangTidy < Processor
    include CPlusPlus

    Schema: untyped

    private
    def construct_result: (untyped stdout) { (untyped) -> untyped } -> untyped
  end
end
