module Runners
  class Processor::ClangTidy < Processor
    include CPlusPlus

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[Schema::cplusplus_runner_config]
    end
    Schema: SchemaClass

    private
    def construct_result: (untyped stdout) { (untyped) -> untyped } -> untyped
  end
end
