module Runners
  class Processor::Coffeelint < Processor
    include Nodejs

    class SchemaClass < StrongJSON
      def runner_config: () -> StrongJSON::Type::Object[Schema::base_runner_config]
    end
    Schema: SchemaClass

    CONSTRAINTS: Hash[String, Nodejs::Constraint]

    private
    def config_file: () -> Array[String]
  end
end
