module Runners
  class Processor::Eslint < Processor
    include Nodejs

    Schema: untyped
    CONSTRAINTS: Hash[String, Constraint]
    CUSTOM_FORMATTER: String
    DEFAULT_ESLINT_CONFIG: String
    DEFAULT_TARGET: String

    private
    def target: () -> untyped
    def eslint_config: () -> untyped
    def ext: () -> untyped
    def ignore_path: () -> untyped
    def ignore_pattern: () -> untyped
    def no_ignore: () -> untyped
    def global: () -> untyped
    def quiet: () -> untyped
    def normalize_severity: (untyped severity) -> untyped
    def parse_result: (untyped result) { (untyped) -> untyped } -> untyped
    def run_analyzer: (?config: untyped? config) -> untyped
    def no_linting_files?: (untyped stderr) -> untyped
    def no_eslint_config?: (untyped stderr) -> untyped
  end
end
