module Runners
  class Processor::Goodcheck < Processor
    include Ruby

    Schema: untyped

    CONSTRAINTS: Hash[String, Array[String]]
    DEFAULT_TARGET: String
    DEFAULT_CONFIG_FILE: String

    private
    def goodcheck_test: () -> untyped
    def goodcheck_check: () -> untyped
  end
end
