module Runners
  class Processor::Misspell < Processor
    Schema: untyped

    DEFAULT_TARGET: String

    private
    def run_analyzer: () -> untyped
    def cli_args: () -> untyped
    def locale: () -> untyped
    def ignore: () -> untyped
    def analysis_targets: () -> untyped
    def delete_targets: () -> (nil | untyped)
  end
end
