module Runners
  class Processor::Tyscan < Processor
    include Nodejs

    Schema: untyped

    CONSTRAINTS: Hash[String, Nodejs::Constraint]
    DEFAULT_CONFIG_FILE: String

    private
    def tyscan_test: () -> untyped
    def tyscan_scan: () -> untyped
  end
end
