FROM sider/devon_rex_base:2.21.0

COPY --chown=<%= chown %> images/clang_tidy/packages.list ${RUNNER_USER_HOME}/

USER root
RUN apt-get update && \
    cat ${RUNNER_USER_HOME}/packages.list | xargs apt-get install -y --no-install-recommends && \
    apt-get clean && \
    echo "analyzer_runner ALL=NOPASSWD: /usr/bin/apt-get" >> /etc/sudoers
USER $RUNNER_USER

<%= render_erb 'images/Dockerfile.base.erb' %>
<%= render_erb 'images/Dockerfile.end.erb' %>
