FROM sider/devon_rex_npm:2.45.9

<%= render_erb 'images/Dockerfile.base.erb' %>

# Install the default version
COPY --chown=<%= chown %> images/<%= analyzer %>/package.json ${RUNNERS_DEPS_DIR}/
RUN cd "${RUNNERS_DEPS_DIR}" && \
    npm install --strict-peer-deps --ignore-scripts --engine-strict --no-progress --no-save && \
    rm package*.json
ENV PATH ${RUNNERS_DEPS_DIR}/node_modules/.bin:${PATH}
# We can't use NODE_PATH
# See the details here: https://github.com/sider/runners/issues/2636
RUN ln -s "${RUNNERS_DEPS_DIR}"/node_modules "${HOME}"
