module Runners
  class Changes
    def self.calculate: (working_dir: Pathname) -> instance
    def self.calculate_by_patches: (working_dir: Pathname, patches: GitDiffParser::Patches) -> instance
    def self.all_files_in: (Pathname) -> Array[Pathname]

    attr_reader changed_paths: Set[Pathname]
    attr_reader unchanged_paths: Set[Pathname]
    attr_reader patches: GitDiffParser::Patches | nil

    def initialize: (changed_paths: Array[Pathname], unchanged_paths: Array[Pathname], patches: GitDiffParser::Patches | nil) -> void
    def delete_unchanged: (dir: Pathname, ?except: Array[String], ?only: Array[String]) -> Array[Pathname]
    def include?: (Issue) -> bool

    private
    def deletable?: (Pathname, Pathname, Array[String], Array[String]) -> bool
  end
end
