module Runners
  interface _IO
    def write: (*_ToS) -> void
    def flush: () -> void
    def flush!: () -> void
    def respond_to?: (Symbol) -> bool
  end

  class IO
    attr_reader ios: Array[::IO | _IO]

    def initialize: (*(::IO | _IO)) -> void
    def write: (*_ToS) -> void
    def flush: () -> void
    def flush!: () -> void
  end
end
