class Runners::Ruby::LockfileLoader
  include Tmpdir

  attr_reader root_dir: Pathname
  attr_reader shell: Shell

  def initialize: (root_dir: Pathname, shell: Shell) -> void
  def ensure_lockfile: [X] () { (Lockfile) -> [X] } -> [X]

  private
  def gemfile_path: () -> Pathname
  def gemfile_lock_path: () -> Pathname
  def generate_lockfile: (Pathname) -> Pathname?
end

class Runners::Ruby::LockfileLoader::InvalidGemfileLock < InstallGemsFailure
end
